// Validates translation files against their English sources:
//   package.nls.json            ← %keys% referenced by package.json
//   package.nls.<lang>.json     ← package.nls.json
//   l10n/bundle.l10n.<lang>.json ← l10n/bundle.l10n.json (generated by `npm run l10n:export`)
//
// Errors: package.json keys missing from package.nls.json, stale keys in a translation,
// placeholder mismatches. Missing translations are warnings unless --strict is passed.
import { readFileSync, readdirSync, existsSync } from 'fs';

const strict = process.argv.includes('--strict');
const errors = [];
const warnings = [];

const readJson = file => JSON.parse(readFileSync(file, 'utf8'));
const messageOf = v => (typeof v === 'string' ? v : v.message);
const placeholders = s => [...s.matchAll(/\{[^{}]+\}/g)].map(m => m[0]).sort().join(' ');

function compare(sourceFile, source, translationFile) {
  const translation = readJson(translationFile);
  for (const key of Object.keys(source)) {
    if (!(key in translation)) {
      warnings.push(`${translationFile}: missing translation for ${JSON.stringify(key)}`);
    } else if (placeholders(messageOf(source[key])) !== placeholders(messageOf(translation[key]))) {
      errors.push(`${translationFile}: placeholders differ from ${sourceFile} for ${JSON.stringify(key)}`);
    }
  }
  for (const key of Object.keys(translation)) {
    if (!(key in source)) errors.push(`${translationFile}: stale key ${JSON.stringify(key)} (not in ${sourceFile})`);
  }
}

// package.json ↔ package.nls.json
const nls = readJson('package.nls.json');
const referenced = new Set([...readFileSync('package.json', 'utf8').matchAll(/"%([^%"]+)%"/g)].map(m => m[1]));
for (const key of referenced) {
  if (!(key in nls)) errors.push(`package.json references %${key}% but package.nls.json does not define it`);
}
for (const key of Object.keys(nls)) {
  if (!referenced.has(key)) errors.push(`package.nls.json: unused key ${JSON.stringify(key)}`);
}
for (const file of readdirSync('.').filter(f => /^package\.nls\.[\w-]+\.json$/.test(f))) {
  compare('package.nls.json', nls, file);
}

// l10n/bundle.l10n.json ↔ l10n/bundle.l10n.<lang>.json
const bundleFile = 'l10n/bundle.l10n.json';
if (existsSync(bundleFile)) {
  const bundle = readJson(bundleFile);
  for (const file of readdirSync('l10n').filter(f => /^bundle\.l10n\.[\w-]+\.json$/.test(f))) {
    compare(bundleFile, bundle, `l10n/${file}`);
  }
}

for (const w of warnings) console.log(`warning: ${w}`);
for (const e of errors) console.log(`error: ${e}`);
const failed = errors.length > 0 || (strict && warnings.length > 0);
console.log(`l10n:check — ${errors.length} error(s), ${warnings.length} warning(s)${failed ? '' : ' ✓'}`);
// exitCode rather than process.exit(): exiting immediately can drop buffered output on pipes (CI logs).
process.exitCode = failed ? 1 : 0;
